"""Update models.py schema

Revision ID: 181eb04d3ec3
Revises: 642b5d96f10f
Create Date: 2025-04-16 19:13:07.448407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181eb04d3ec3'
down_revision = '642b5d96f10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('korting', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursus', schema=None) as batch_op:
        batch_op.drop_column('korting')

    # ### end Alembic commands ###
