"""Wijzig datetime kolom naar DateTime in Les

Revision ID: 3b523586cf57
Revises: 3c8ba8c6a8e6
Create Date: 2025-04-16 13:19:07.778372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b523586cf57'
down_revision = '3c8ba8c6a8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('les', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('les', schema=None) as batch_op:
        batch_op.alter_column('datetime',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
