"""Initial migration

Revision ID: 3c8ba8c6a8e6
Revises: 
Create Date: 2025-04-16 12:43:29.855113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8ba8c6a8e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_les')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    op.create_table('_alembic_tmp_les',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_klant', sa.INTEGER(), nullable=False),
    sa.Column('id_docent', sa.INTEGER(), nullable=False),
    sa.Column('id_cursus', sa.INTEGER(), nullable=False),
    sa.Column('locatie', sa.VARCHAR(length=50), nullable=False),
    sa.Column('datetime', sa.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
