"""Update database schema

Revision ID: b65013e19bf5
Revises: 3b523586cf57
Create Date: 2025-04-16 15:19:16.217051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65013e19bf5'
down_revision = '3b523586cf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('les', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inschrijving_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_les_inschrijving', 'inschrijving', ['inschrijving_id'], ['cursus_id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('les', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inschrijving_id')

    # ### end Alembic commands ###
